name: Quality Assurance

on:
  pull_request:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
    branches: 
      - main

jobs:   
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: Cache mvn dependencies
      uses: actions/cache@v2.1.5
      env:
        cache-name: mvn-deps
      with:
        path: ~/.m2
        key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
        restore-keys: ${{ env.cache-name }}-
    - name: Test with Maven
      run: mvn clean verify
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
